sys2do/views/purchase.py
# -*- coding: utf-8 -*-
'''
Created on 2013-4-11

@author: cl.lam
'''
from datetime import datetime as dt
from werkzeug.exceptions import abort
import flask
import traceback
from flask import current_app as app
from flask import g, render_template, flash, session, redirect, url_for, request, request_finished
from flask.blueprints import Blueprint
from sqlalchemy.sql.expression import desc, and_
from flask.helpers import jsonify

from sys2do.views import BasicView
from sys2do.util.decorator import templated, activetab, mypaginate, \
    allPermission
from sys2do.util.logic_helper import getCurrentShopID, checkLogin, \
    getCurrentUserID, getCurrentShopProfile, makeUpdateLog, checkUpdate
from sys2do.constant import *

from sys2do.util.common import _gld, _gp, _g, multiupload
from sys2do.model import db, Product, qry, SysLog, SysFile, InventoryLocation, \
    PO, InventoryProduct, PODtl, InventoryNote, \
    InventoryNoteDtl, FinNote, FinNoteDtl, ItemBalance
from sys2do.util.wt_helper import MyDateField

from sys2do.util.barcode_helper import genBarcodeFile
from sys2do.util.exception import MoreThanStockExp


__all__ = ['bpPrh']


bpPrh = Blueprint( 'bpPrh', __name__, )

@bpPrh.before_request
def _b():
    return checkLogin()


class PurchaseView( BasicView ):

    template_folder = 'prh'


    @templated( "index.html" )
    @activetab( TAB_HOME )
    @mypaginate( 'result' )
    @allPermission( ['PURCHASE_VIEW'] )
    def index( self ):

        if request.method == 'POST':
            form = SrhForm( request.form )
            session[url_for( '.view' )] = form
        else:
            form = session.get( url_for( '.view' ), SrhForm( request.form ) )
        form.url = url_for( '.view' )
        spobj = getCurrentShopProfile()

        cds = [ PO.active == 0, PO.shopID == spobj.shopID ]
        if form.no.data : cds.append( PO.no.like( '%%%s%%' % form.no.data ) )
        if form.status.data and form.status.data != 'None' :  cds.append( PO.status == form.status.data )
        if form.createTimeFrom.data : cds.append( PO.createTime > form.createTimeFrom.data )
        if form.createTimeTo.data : cds.append( PO.createTime < form.createTimeTo.data )
        result = PO.iall( conditions = cds, order_by = desc( PO.createTime ) )

        return {'form' : form , 'result' : result}



    @templated( "add.html" )
    @allPermission( ['PURCHASE_CREATE'] )
    def add( self ):
        sid = getCurrentShopID()
        if request.method != 'POST':
            return {}
        try:
            params = _gld( 'supplierID', 'att', 'tel', 'mobile', 'remark' )
            params['shopID'] = sid
            params['createById'] = getCurrentUserID()
            params['updateById'] = getCurrentUserID()
            params['attachment'] = multiupload()

            hdr = PO.create( params )
            db.add( hdr )
            amount, realAmount = 0, 0
            for ( k, v ) in _gp( "product_" ):
                if not v : continue
#                 pid = k.split( "_" )[1]
                pid = v
                qty = int( _g( "qty_" + pid ) or 0 )
                pPrice = float( _g( 'pPrice_%s' % pid ) or 0 )
                realPrice = float( _g( 'realPrice_%s' % pid ) or 0 )
                rm = _g( 'remark_%s' % pid )
                dtl = PODtl( hdr = hdr, pdtID = pid, qty = qty, price = pPrice, discounts = 1, realPrice = realPrice, remark = rm )
                amount += pPrice * qty
                realAmount += realPrice * qty
                dtl.copyPdtInfo( Product.get( pid ) )
                db.add( dtl )

            hdr.amount = amount
            hdr.realAmount = realAmount
            db.flush()
            db.add( SysLog( refClz = hdr.__class__.__name__, type = LOG_TYPE_CREATE, refID = hdr.id, ) )
            db.commit()
            flash( MSG_SAVE_SUCC, MESSAGE_INFO )
        except:
            self._error( traceback.format_exc() )
            db.rollback()
            flash( MSG_SERVER_ERROR, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )
        else:
            return redirect( url_for( '.view', action = 'view', id = hdr.id ) )


    @templated( 'view.html' )
    def view( self ):
        obj = PO.get( _g( 'id' ) )
        return {'obj' : obj}


    @templated( 'update.html' )
    def update( self ):
        pid = _g( 'id' )
        if not pid :
            flash( MSG_NO_ID_SUPPLIED, MESSAGE_ERROR )
            return redirect( url_for( ".view" ) )

        obj = PO.get( pid )
        if not obj :
            flash( MSG_RECORD_NOT_EXIST, MESSAGE_ERROR )
            return redirect( url_for( ".view" ) )

        if request.method != 'POST': return {'obj' : obj}

        try:
            oldCopy = obj.serialize()
            extLog = []

            params = _gld( 'supplierID', 'att', 'tel', 'mobile', 'remark' )
            obj.update( params )
            obj.updateTime = dt.now()
            obj.updateById = getCurrentUserID()

            oldaset = set( map( lambda v : unicode( v.id ), obj.attachment ) )
            newaset = set( filter( bool, _g( 'attachment', '' ).split( "|" ) ) )
            deltedAtm = oldaset.difference( newaset )
            if deltedAtm :
                delAtms = qry( SysFile ).filter( SysFile.id.in_( list( deltedAtm ) ) )
                extLog.extend( [u'删除附件[%s]。' % da.name for da in delAtms] )

            if newaset : obj.attachment = sorted( list( newaset ) ) + multiupload()
            else : obj.attachment = multiupload()

            amount, realAmount = 0, 0

            for d in obj.dtls:
                if not _g( 'oldproduct_%s' % d.id ) :
                    extLog.append( u'删除商品[%s],数量[%s],备注[%s]。' % ( d.pdtname, d.qty, d.remark ) )
                    d.active = 1
                oldDtl = d.serialize()
                d.price = _g( 'oldpPrice_%s' % d.id ) or 0
                d.realPrice = _g( 'oldrealPrice_%s' % d.id ) or 0
                d.qty = _g( 'oldqty_%s' % d.id ) or 0
                d.remark = _g( 'oldremark_%s' % d.id )
                amount += float( d.price ) * int( d.qty )
                realAmount += float( d.realPrice ) * int( d.qty )
                newDtl = d.serialize()

                tmpLog = checkUpdate( oldDtl, newDtl )
                if tmpLog : extLog.extend( [u'修改商品 [%s]：' % d.pdtname, ] + tmpLog )
                d.copyPdtInfo( d.pdt )

            for ( k, v ) in _gp( "product_" ):
                if not v : continue
                pid = v
                qty = int( _g( "qty_" + pid ) or 0 )
                pPrice = float( _g( 'pPrice_%s' % pid ) or 0 )
                realPrice = float( _g( 'realPrice_%s' % pid ) or 0 )
                rm = _g( 'remark_%s' % pid )
                dtl = PODtl( hdr = obj, pdtID = pid, qty = qty, price = pPrice, discounts = 1, realPrice = realPrice, remark = rm )
                amount += pPrice * qty
                realAmount += realPrice * qty
                dtl.copyPdtInfo( Product.get( pid ) )    # copy the product info the dtl
                db.add( dtl )

            obj.amount = amount
            obj.realAmount = realAmount

            newCopy = obj.serialize()
            makeUpdateLog( obj, oldCopy, newCopy, extLog )
            flash( MSG_SAVE_SUCC, MESSAGE_INFO )
            db.commit()
        except:
            self._error( traceback.format_exc() )
            db.rollback()
            flash( MSG_SERVER_ERROR, MESSAGE_ERROR )
        return redirect( url_for( ".view", action = 'view', id = obj.id ) )



    @allPermission( ['PURCHASE_APPROVE'] )
    def app( self ):
        try:
            spro = getCurrentShopProfile()
            prhivt = InventoryLocation.getPurchaseIvt()
            obj = PO.get( _g( 'id' ) )
            obj.status = PO_APPROVE
            # create inventory in note
            notehdr = InventoryNote.create( dict( shopID = spro.shopID, direction = IVTNT_IN,
                                                  refer = obj.no, ivtID = prhivt.id, status = IVTNT_NEW ) )
            notehdr.comeFrom = ( obj, obj.id )
            # create fin in note
            finhdr = FinNote.create( {'direction' : FIN_OUT, 'amount' : obj.realAmount,
                                     'refer' : obj.no, 'status' : FIN_NEW , 'accountID' : None,
                                     'shopID' : spro.shopID , 'issueTo' : unicode( obj.supplier ),
                                     'issueFrom' : unicode( obj.supplier.fullName ),
                                     'currencyID' : obj.currencyID, } )
            finhdr.comeFrom = ( obj, obj.id )
            db.add_all( [notehdr, finhdr, ] )
            for d in obj.dtls:
                ivtntDtl = InventoryNoteDtl.create( dict( hdr = notehdr, pdtID = d.pdtID, qty = d.qty, sIvtLtnID = prhivt.id, dIvtLtnID = spro.inventoryID ) )
                ivtntDtl.copyPdtInfo( d.pdt )
                db.add( ivtntDtl )
                db.add( FinNoteDtl.create( {'hdr' : finhdr, 'itemName' : d.pdt.name, 'desc' : d.pdt.makeDesc() , 'refer' : d.id,
                                            'price' : d.realPrice, 'qty' : d.qty, 'amount' : d.qty * d.realPrice, } ) )

                #===============================================================
                # 1. add the qty to the pruchase inventory,
                # 2. to move the product from purchase inventory to the shop's
                #    root inventory
                #===============================================================
                InventoryProduct.addOrUpdate( prhivt.id, d.pdtID, d.qty, 0, 0 )
#                 InventoryProduct.goingToMove( ivtntDtl.sIvtLtnID, ivtntDtl.dIvtLtnID, d.pdtID, d.qty )

                # create item and log the purchase price
                items = d.pdt.genItem( d.qty )
                for item in items :
                    item.pPrice, item.ivtID = d.realPrice, prhivt.id
                    db.add( ItemBalance( item = item, pPrice = d.realPrice, pRefer = obj.no ) )

            db.flush()
            # add the log

sys2do/templates/prh/add.html
{% extends "master.html" %}
{% block subtitle %} - 采购管理 - 创建采购单{% endblock %}

{% block extCSS %}
<style type="text/css">
    .atmtemplate{
        display : none;
    }
    
    .modal{
        width : 860px;
        margin-left: -460px;
    }
</style>
{% endblock %}

{% block extJS %}
<script src="{{url_for('static', filename='js/customize/purchase_add.js')}}" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">
//<![CDATA[   
    var extPdts = [];

    $(document).ready(function(){
        $(".priceclz,.qtyclz").change(function(){
            countAmount();
        })        
    });
    

    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        
        if(!$("#supplierID").val()){
            msg.push('请选择供应商！');
            $("#supplierID").addClass('err');
        }
        
        
        var pflag = false;
        var qflag = true; 
        $("input[name^='product_']").each(function(){
            var t = $(this);
            if(t.val()){ 
                pflag = true; 
                var pid = t.attr('name').split("_")[1]
                if(!$("input[name='qty_"+pid+"']").val()){ qflag = false; }
                if(!$("input[name='realPrice_"+pid+"']").val()){ qflag = false; }
            }
        });
        
        if(!pflag){ msg.push('请填写至少一个商品名称！'); }
        if(!qflag){ msg.push('请填写商品的数量以及价格！'); }
        
        var flag = true;
        $(".num").each(function(){
            var t = $(this);
            if( t.val() && !check_number(t.val())){
                flag = false;
                t.addClass('err');
            }
        })
        
        if(!flag){
            msg.push('请正确填写数量以及价钱,只填写数字!')
        }
        
        if(msg.length > 0){
            alertError(msg);
            return false;
        }else{
            $("form").submit();
        }
    }
    
    function toCancel(){
        redirect_alert("{{MSG_LEAVE_WITHOUT_SAVING}}","{{url_for('bpPrh.view')}}")
    }        
        
//]]>
</script>
{% endblock %}


{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">基础信息</a></li>
          <li><a href="{{url_for('bpPrh.view')}}">采购管理</a></li>
          <li class="active">创建采购单</li>
        </ol>
    </div>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="toSubmit()">{{BTN_SUBMIT}}</button></div>
            <div class="btn-group"><button class="btn btn-inverse" onclick="toCancel()">{{BTN_CANCEL}}</button></div>
        </div>
    </div>
    <div class="row">
    <form class="" method='POST' action="{{url_for('bpPrh.view',action='add')}}" enctype="multipart/form-data">
        <fieldset>
            <legend>采购单详情</legend>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="supplierID">供应商<span style='color:red'>*</span></label></label>
                    <div class="controls">
                        <select id="supplierID" name="supplierID" onchange="changeSupplier()">
                            <option value=""></option>
                            {% for s in getMaster('Supplier') %}
                                <option value="{{s.id}}">{{s}}</option>
                            {% endfor %}
                        </select>
                        {% if getAllPermission(['SUPPLIER_CREATE',])%}
                            <a href="#" onclick="refreshMaster('supplierID','Supplier')"><i class="glyphicon glyphicon-refresh"></i></a>
                            <a target="_blank" href="{{url_for('bpSpl.view',action='add')}}"><i class="glyphicon glyphicon-plus"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div class="control-group controls-row">
                    <label for="att" class="control-label"><label for="att">联系人<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" id="att" name="att" value=""/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="tel" class="control-label"><label for="tel">联系电话<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="tel" id="tel" value=""/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="mobile" class="control-label"><label for="mobile">联系手机<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="mobile" id="mobile" value=""/></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="createTime" class="control-label"><label for="createTime">采购日期</label></label>
                    <div class="controls"><input type="text" name="createTime" value="{{now()|fd}}" class="datepicker"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="createBy" class="control-label"><label for="createBy">经办人</label></label>
                    <div class="controls"><input type="text" name="createBy" value="{{session['user_profile']['name']}}" readonly="true"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="remark">备注</label></label>
                    <div class="controls"><textarea name="remark" id="remark"></textarea></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="amount" class="control-label"><label for="amount">总金额<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="amount" id="amount" value="" class="num" readonly="true"/></div>
                </div>
                <div class="control-group">
                  <label class="control-label" for="attachment">附件</label>
                  <div class="controls">
                      <ul id="atmul" class="list-unstyled">
                          <li><input type="file" name="atm_10"/><a href="#" onclick="addAtm('atmtemplate','atmmk','#atmul')"><i class="glyphicon glyphicon-plus"></i></a></li>
                          <li class="atmtemplate"><input type="file" name="atm_x"/><a href="#" onclick="delAtm(this,'atmmk')"><i class="glyphicon glyphicon-minus"></i></a></li>
                      </ul>
                  </div>
                </div>
            </div>          
            <div class="col-md-12">
                <label>添加商品</label>
                <select id="field">
                    <option value="no">商品编号</option>
                    <option value="name">商品名称</option>
                </select>
                <input type="text" id="fieldValue" class="input-xxlarge" data-provide="typeahead" autocomplete="off" placeholder="请输入商品相关信息，回车添加商品并清空输入框信息"/>
                <table class="table table-bordered" id="pdt_tb">
                    <thead>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="col-md-2">商品编号</td>
                            <td>商品名称</td>
                            <td>商品类型</td>
                            <td>商品价钱</td>
                            <td>采购价钱</td>
                            <td>数量</td>
                            <td>备注</td>
                        </tr>
                    </thead>
                    <tbody id="pdtlist">
    
                    </tbody>                
                </table>
            </div>
        </fieldset>            
                      
    </form>
    </div>
</div>


{{mymacros.render_recent_prh_price()}}

{% endblock %}

sys2do/templates/prh/index.html
{% extends "master.html" %}
{% block subtitle %} - 采购管理{% endblock %}


{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">主面板</a></li>
          <li class="active">采购管理</li>
        </ol>
    </div>

    <div class="row">
        <div class="panel panel-primary">
            <div class="panel-heading"><h4 class="panel-title">输入查询条件</h4></div>
            <div class="panel-body">
                <div class="row">{{mymacros.render_search_form(form,3)}}</div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="btn-toolbar pull-right">
                            <div class="btn-group"><button type="button" class="btn btn-default" onclick="$('form').submit()">{{BTN_SEARCH}}</button></div>
                            {% if getAllPermission(['PURCHASE_CREATE',]) %}
                                <div class="btn-group"><a href="{{url_for('bpPrh.view',action='add')}}" class="btn btn-primary">创建采购单</a></div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <td class="col-md-2">系统编号</td>
                        <td>供应商</td>
                        <td class="col-md-2">实际总金额(元)</td>
                        <td class="col-md-1">状态</td>
                        <td class="col-md-2">经办人</td>
                        <td class="col-md-2">创建时间</td>
                    </tr>
                </thead>
                <tbody>
                    {% for r in result.items %}
                        <tr>
                            <td><a href="{{url_for('bpPrh.view',action='view',id=r.id)}}">{{r.no}}</a></td>
                            <td>{{r.supplier}}</td>
                            <td>{{r.realAmount}}</td>
                            <td>{{r.status|ss(c='PO')}}</td>
                            <td>{{r.createBy}}</td>
                            <td>{{r.createTime|ft}}</td>
                        </tr>
                    {% endfor %}
                </tbody>                
            </table>
            {{mymacros.mypaginate(result)}}
        
        </div>
        
    </div>
</div>
{% endblock %}

sys2do/templates/prh/update.html
{% extends "master.html" %}
{% block subtitle %} - 采购管理 - 更改采购单{% endblock %}

{% block extCSS %}
<style type="text/css">
    .atmtemplate{
        display : none;
    }
    
    .modal{
        width : 860px;
        margin-left: -460px;
    }
</style>
{% endblock %}

{% block extJS %}
<script src="{{url_for('static', filename='js/customize/purchase_add.js')}}" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    
    var extPdts = [];
    {% for d in obj.dtls %}
        extPdts.push('{{d.pdt.no}}');
    {% endfor %}    
    
    var extAtm = [];
    {% for a in obj.attachment %}
        extAtm.push({{a.id}});
    {% endfor %}

    $(document).ready(function(){
        $(".priceclz,.qtyclz").change(function(){
            countAmount();
        })        
    });
    

    function delItem(){
        
    }
    
    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        
        if(!$("#supplierID").val()){
            msg.push('请选择供应商！');
            $("#supplierID").addClass('err');
        }
        
        
        var pflag = false;
        var qflag = true; 
        $("input[name^='product_']").each(function(){
            var t = $(this);
            if(t.val()){ 
                pflag = true; 
                var pid = t.attr('name').split("_")[1]
                if(!$("input[name='qty_"+pid+"']").val()){ qflag = false; }
                if(!$("input[name='realPrice_"+pid+"']").val()){ qflag = false; }
            }
        });
        
        $("input[name^='oldproduct_']").each(function(){
            var t = $(this);
            if(t.val()){ 
                pflag = true; 
                var pid = t.attr('name').split("_")[1]
                if(!$("input[name='oldqty_"+pid+"']").val()){ qflag = false; }
                if(!$("input[name='oldrealPrice_"+pid+"']").val()){ qflag = false; }
            }
        });
        
        if(!pflag){ msg.push('请填写至少一个商品名称！'); }
        if(!qflag){ msg.push('请填写商品的数量以及价格！'); }
        
        var flag = true;
        $(".num").each(function(){
            var t = $(this);
            if( t.val() && !check_number(t.val())){
                flag = false;
                t.addClass('err');
            }
        })
        
        if(!flag){
            msg.push('请正确填写数量以及价钱,只填写数字!')
        }
        
        if(msg.length > 0){
            alertError(msg);
            return false;
        }else{
            $("form").submit();
        }
    }
    
    function toCancel(){
        redirect_alert("{{MSG_LEAVE_WITHOUT_SAVING}}","{{url_for('bpPrh.view')}}")
    }        
        
//]]>
</script>
{% endblock %}


{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">基础信息</a></li>
          <li><a href="{{url_for('bpPrh.view')}}">采购管理</a></li>
          <li class="active">更改采购单</li>
        </ol>
    </div>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="toSubmit()">{{BTN_SUBMIT}}</button></div>
            <div class="btn-group"><button class="btn btn-inverse" onclick="toCancel()">{{BTN_CANCEL}}</button></div>
        </div>
    </div>
    <div class="row">
    <form class="" method='POST' action="{{url_for('bpPrh.view',action='update')}}" enctype="multipart/form-data">
        <input type="hidden" name="id" value="{{obj.id}}"/>
        <input type="hidden" name="attachment" id="attachment" value="{{obj.attachment|join('|',attribute='id')}}"/>
        <fieldset>
            <legend>采购单详情</legend>   
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="refer">系统编号</label></label>
                    <div class="controls">
                        {{obj.no}}
                    </div>
                </div>
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="supplierID">供应商<span style='color:red'>*</span></label></label>
                    <div class="controls">
                        <select id="supplierID" name="supplierID" onchange="changeSupplier()">
                            <option value=""></option>
                            {% for s in getMaster('Supplier') %}
                                {% if s.id == obj.supplierID %}
                                    <option value="{{s.id}}" selected="true">{{s}}</option>
                                {% else %}
                                    <option value="{{s.id}}">{{s}}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        {% if getAllPermission(['SUPPLIER_CREATE',])%}
                            <a href="#" onclick="refreshMaster('supplierID','Supplier')"><i class="glyphicon glyphicon-refresh"></i></a>
                            <a target="_blank" href="{{url_for('bpSpl.view',action='add')}}"><i class="glyphicon glyphicon-plus"></i></a>
                        {% endif %}
                    </div>
                </div>
                <div class="control-group controls-row">
                    <label for="att" class="control-label"><label for="att">联系人<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="att" id="att" value="{{obj.att|f}}"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="tel" class="control-label"><label for="tel">联系电话<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="tel" id="tel" value="{{obj.tel|f}}"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="mobile" class="control-label"><label for="mobile">联系手机<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="mobile" id="mobile" value="{{obj.mobile|f}}"/></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="createTime" class="control-label"><label for="createTime">采购日期</label></label>
                    <div class="controls"><input type="text" name="createTime" value="{{obj.createTime|fd}}" class="datepicker"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="createBy" class="control-label"><label for="createBy">经办人</label></label>
                    <div class="controls"><input type="text" name="createBy" value="{{obj.createBy.name}}" readonly="true"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="remark">备注</label></label>
                    <div class="controls"><textarea name="remark" id="remark">{{obj.remark|f}}</textarea></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="amount" class="control-label"><label for="amount">总金额<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="amount" id="amount" value="{{obj.realAmount|f}}" class="num" readonly="true"/></div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="control-group">
                  <label class="control-label" for="attachment">附件</label>
                  <div class="controls">
                      {{mymacros.render_edit_all_attachment(obj.attachment)}}
                      <ul id="atmul" class="list-unstyled">
                          <li><input type="file" name="atm_10"/><a href="#" onclick="addAtm('atmtemplate','atmmk','#atmul')"><i class="glyphicon glyphicon-plus"></i></a></li>
                          <li class="atmtemplate"><input type="file" name="atm_x"/><a href="#" onclick="delAtm(this,'atmmk')"><i class="glyphicon glyphicon-minus"></i></a></li>
                      </ul>
                  </div>
                </div>                                
            </div>                 
            <div class="col-md-12">
                <label>添加商品</label>
                <select id="field">
                    <option value="no">商品编号</option>
                    <option value="name">商品名称</option>
                </select>
                <input type="text" id="fieldValue" class="input-xxlarge" data-provide="typeahead" autocomplete="off" placeholder="请输入商品相关信息，回车添加商品并清空输入框信息"/>
                <table class="table table-bordered" id="pdt_tb">
                    <thead>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="col-md-2">商品编号</td>
                            <td>商品名称</td>
                            <td>商品类型</td>
                            <td>商品价钱</td>
                            <td>采购价钱</td>
                            <td>数量</td>
                            <td>备注</td>
                        </tr>
                    </thead>
                    <tbody id="pdtlist">
                        {% for d in obj.dtls%}
                            <tr class="done">
                                <td><a href="#" onclick="showPrice({{d.pdt.no}})" title="显示最近采购该商品记录"><i class="glyphicon glyphicon-time"></i></a><br /><a href="#" onclick="rmProduct(this)"><i class="glyphicon glyphicon-remove"></i></a></td>
                                <td><a href="{{url_for('bpPdt.view',action='view',id=d.pdt.id)}}" target="_blank" class="pdtlink">{{d.pdt.no}}</a><input type="hidden" name="oldproduct_{{d.id}}" value="{{d.id}}"/></td>
                                <td>{{d.pdt.name}}</td>
                                <td>{{d.pdt.type}}</td>
                                <td>{{d.pdt.pPrice}}<input type="hidden" name="oldpPrice_{{d.id}}" value="{{d.pdt.pPrice}}"/></td>
                                <td><input type="text" name="oldrealPrice_{{d.id}}" class="col-md-2 num priceclz" value="{{d.realPrice}}"/></td>
                                <td><input type="text" name="oldqty_{{d.id}}" class="col-md-1 num qtyclz" value="{{d.qty}}"/></td>
                                <td><textarea name="oldremark_{{d.id}}">{{d.remark|f}}</textarea></td>
                            </tr>
                        {% endfor %}
                    </tbody>                
                </table>
            </div>
        </fieldset>           
    </form>
    </div>
</div>
    

{{mymacros.render_recent_prh_price()}}

{% endblock %}