sys2do/views/finance.py
# -*- coding: utf-8 -*-
'''
Created on 2013-4-11
@author: cl.lam
'''
import traceback
from datetime import datetime as dt
from sqlalchemy.sql.expression import and_, desc
import flask
from flask import current_app as app
from flask import g, render_template, flash, session, redirect, url_for, request, abort
from flask.blueprints import Blueprint

from sys2do.views import BasicView
from sys2do.util.decorator import templated, loginRequired, allPermission, \
    anyPermission, mypaginate
from sys2do.util.logic_helper import getPermission, getCurrentShopProfile, \
    checkLogin, getCurrentUserID, makeUpdateLog, checkUpdate
from sys2do.model import qry, db, FinNote, FinNoteDtl, FinAccount, SysLog, SysFile
from sys2do.util.wt_helper import MyDateField
from sys2do.constant import FIN_IN, FIN_OUT, MSG_SAVE_SUCC, MESSAGE_INFO, \
    MSG_NOT_ENOUGH_PARAMS, MESSAGE_ERROR, MSG_SERVER_ERROR, FIN_NEW, \
    MSG_RECORD_NOT_EXIST, FIN_APPROVE, MSG_UPDATE_SUCC, MSG_NO_SUCH_ACTION, \
    MSG_DELETE_SUCC, INACTIVE, ACTIVE, MSG_NOT_ALL_PARAMS_OK, LOG_TYPE_CREATE, \
    LOG_TYPE_REJECT, LOG_TYPE_APPROVE, LOG_TYPE_DEL, MSG_NO_PERMISSION, \
    MSG_NO_ID_SUPPLIED, LOG_TYPE_UPDATE
from sys2do.util.common import _gld, _gp, _g, _gl, multiupload
from sys2do.model.interface import getUserID


__all__ = ['bpFin']


bpFin = Blueprint( 'bpFin', __name__, )

@bpFin.before_request
def _b():
    return checkLogin()

class FinanceView( BasicView ):

    template_folder = 'fin'

    @templated( "index.html" )
    @anyPermission( ['FIN_IN_VIEW', 'FIN_OUT_VIEW'] )
    def index( self ):
        if getPermission( 'FIN_IN_VIEW' ) : return redirect( url_for( '.view', action = 'index_in' ) )
        if getPermission( 'FIN_IN_VIEW' ) : return redirect( url_for( '.view', action = 'index_out' ) )


    @templated( "index_in.html" )
    @mypaginate( 'result' )
    @allPermission( ['FIN_IN_VIEW', ] )
    def index_in( self ):
        if request.method == 'POST':
            form = SrhInForm( request.form )
            session[url_for( '.view', action = 'index_in' )] = form
        else:
            form = session.get( url_for( '.view', action = 'index_in' ), SrhInForm( request.form ) )
        form.url = url_for( '.view', action = 'index_in' )

        spobj = getCurrentShopProfile()
        cds = [FinNote.active == ACTIVE, FinNote.shopID == spobj.shopID, FinNote.direction == FIN_IN, ]

        if form.no.data : cds.append( FinNote.no.like( '%%%s%%' % form.no.data ) )
        if form.invoiceNo.data : cds.append( FinNote.invoiceNo.like( '%%%s%%' % form.invoiceNo.data ) )
        if form.issueTo.data : cds.append( FinNote.issueTo.like( '%%%s%%' % form.issueTo.data ) )
        if form.refer.data : cds.append( FinNote.refer.like( '%%%s%%' % form.refer.data ) )
        if form.createTimeFrom.data : cds.append( FinNote.createTime > form.createTimeFrom.data )
        if form.createTimeTo.data : cds.append( FinNote.createTime < form.createTimeTo.data )

        result = FinNote.iall( conditions = cds, order_by = desc( FinNote.createTime ) )
        return {'result' : result, 'form' : form}



    @templated( "index_out.html" )
    @mypaginate( 'result' )
    @allPermission( ['FIN_OUT_VIEW', ] )
    def index_out( self ):
        if request.method == 'POST':
            form = SrhOutForm( request.form )
            session[url_for( '.view', action = 'index_out' )] = form
        else:
            form = session.get( url_for( '.view', action = 'index_out' ), SrhOutForm( request.form ) )
        form.url = url_for( '.view', action = 'index_out' )

        spobj = getCurrentShopProfile()
        cds = [FinNote.active == ACTIVE, FinNote.shopID == spobj.shopID, FinNote.direction == FIN_OUT, ]

        if form.no.data : cds.append( FinNote.no.like( '%%%s%%' % form.no.data ) )
        if form.invoiceNo.data : cds.append( FinNote.invoiceNo.like( '%%%s%%' % form.invoiceNo.data ) )
        if form.issueFrom.data : cds.append( FinNote.issueFrom.like( '%%%s%%' % form.issueFrom.data ) )
        if form.refer.data : cds.append( FinNote.refer.like( '%%%s%%' % form.refer.data ) )
        if form.createTimeFrom.data : cds.append( FinNote.createTime > form.createTimeFrom.data )
        if form.createTimeTo.data : cds.append( FinNote.createTime < form.createTimeTo.data )

        result = FinNote.iall( conditions = cds, order_by = desc( FinNote.createTime ) )
        return {'result' : result, 'form' : form}


    @templated( 'view.html' )
    @anyPermission( ['FIN_IN_VIEW', 'FIN_OUT_VIEW', ] )
    def view( self ):
        fid = _g( 'id' )
        if not id :
            flash( MSG_NOT_ENOUGH_PARAMS, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )
        obj = FinNote.get( fid )
        if not obj :
            flash( MSG_RECORD_NOT_EXIST, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )

        spobj = getCurrentShopProfile()
        return {'obj' : obj , 'accounts' : spobj.accounts}



    @anyPermission( ['FIN_IN_EDIT', 'FIN_OUT_EDIT', ] )
    def add( self ):
        t = _g( 't' )
        if t not in [FIN_IN, FIN_OUT]:
            flash( MSG_NO_SUCH_ACTION, MESSAGE_ERROR )
            return redirect( url_for( 'bpRoot.view' ) )

        if t == FIN_IN and getPermission( 'FIN_IN_EDIT' ):
            return render_template( '%s/add_in.html' % self.template_folder )
        elif t == FIN_OUT and getPermission( 'FIN_OUT_EDIT' ):
            return render_template( '%s/add_out.html' % self.template_folder )

        flash( MSG_NO_PERMISSION, MESSAGE_ERROR )
        return redirect( url_for( 'bpRoot.view' ) )



    @anyPermission( ['FIN_IN_EDIT', 'FIN_OUT_EDIT', ] )
    def saveNew( self ):
        params = _gld( 'direction', 'invoiceNo', 'issueTo', 'refer', 'amount', 'createTime', 'remark' )
        if not params['direction'] or params['direction'] not in [FIN_IN, FIN_OUT, ]:
            flash( MSG_NOT_ENOUGH_PARAMS, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )
        try:
            spobj = getCurrentShopProfile()
            if not params['createTime'] : params['createTime'] = dt.now()
            params['shopID'] = spobj.shopID
            params['status'] = FIN_NEW
            params['attachment'] = multiupload()
            hdr = FinNote.create( params )
            db.add( hdr )
            for k, v in _gp( 'itemName_' ):
                n, did = k.split( "_" )
                if not v : continue

                itemName, desc, price, qty, amount, remark = v, _g( 'desc_%s' % did ), _g( 'price_%s' % did ), _g( 'qty_%s' % did ), _g( 'amount_%s' % did ), _g( 'remark_%s' % did ),

                dtl = FinNoteDtl.create( {'hdr' : hdr , 'itemName' : itemName, 'desc' : desc, 'price' : price,
                                   'qty' : qty, 'amount' : amount, 'remark' : remark} )
                db.add( dtl )
            db.add( SysLog( refClz = hdr.__class__.__name__, type = LOG_TYPE_CREATE, refID = hdr.id, ) )
            db.commit()
            flash( MSG_SAVE_SUCC, MESSAGE_INFO )

        except:
            self._error( traceback.format_exc() )
            db.rollback()
            flash( MSG_SERVER_ERROR, MESSAGE_ERROR )
        if params['direction'] == FIN_IN : url = url_for( '.view', action = 'index_in' )
        elif params['direction'] == FIN_OUT : url = url_for( '.view', action = 'index_out' )
        else : url = url_for( '.view' )
        return redirect( url )


    @anyPermission( ['FIN_IN_EDIT', 'FIN_OUT_EDIT', ] )
    def update( self ):
        fid = _g( 'id' )
        if not fid :
            flash( MSG_NO_ID_SUPPLIED, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )
        obj = FinNote.get( fid )
        if not obj :
            flash( MSG_RECORD_NOT_EXIST, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )

        if obj.direction == FIN_IN and not getPermission( 'FIN_IN_EDIT' ):
            flash( MSG_NO_PERMISSION, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )
        elif obj.direction == FIN_OUT and not getPermission( 'FIN_OUT_EDIT' ):
            flash( MSG_NO_PERMISSION, MESSAGE_ERROR )
            return redirect( url_for( '.view' ) )

        if request.method != 'POST':
            if obj.direction == FIN_IN:
                return render_template( '%s/update_in.html' % self.template_folder, obj = obj )
            else:
                return render_template( '%s/update_out.html' % self.template_folder, obj = obj )
        try:
            oldCopy = obj.serialize()
            extLog = []
            params = _gld( 'invoiceNo', 'issueTo', 'refer', 'amount', 'createTime', 'remark' )
            params['updateById'] = getCurrentUserID()
            params['updateTime'] = dt.now()
            obj.update( params )

            oldaset = set( map( lambda v : unicode( v.id ), obj.attachment ) )
            newaset = set( _g( 'attachment', '' ).split( "|" ) )
            deltedAtm = oldaset.difference( newaset )
            if deltedAtm :
                delAtms = qry( SysFile ).filter( SysFile.id.in_( list( deltedAtm ) ) )
                extLog.extend( [u'删除附件[%s]。' % da.name for da in delAtms] )
            if newaset : obj.attachment = sorted( list( newaset ) ) + multiupload()
            else : obj.attachment = multiupload()

            for d in obj.dtls:
                if not _g( 'olditemName_%s' % d.id ) :
                    extLog.append( u'删除子项目[%s],数量[%s],备注[%s]。' % ( d.itemName, d.qty, d.remark ) )
                    d.active = 1
                oldDtl = d.serialize()
                d.itemName = _g( 'olditemName_%s' % d.id )
                d.desc = _g( 'olddesc_%s' % d.id )
                d.price = _g( 'oldprice_%s' % d.id )
                d.qty = _g( 'oldqty_%s' % d.id )
                d.amount = _g( 'oldamount_%s' % d.id )
                d.remark_ = _g( 'oldremark_%s' % d.id )

                newDtl = d.serialize()
                tmpLog = checkUpdate( oldDtl, newDtl )

sys2do/templates/fin/account_add.html
{% extends "master.html" %}
{% block subtitle %} - 主面板 - 财务管理 - 创建账户{% endblock %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        if(!$("#name").val()){
            msg.push('请填写商店的账户名称！');
            $("#name").addClass('err');
        }
        
        if(!$("#bankID").val()){
            msg.push('请填写商店的账户银行！');
            $("#bankID").addClass('err');
        }
        
        if(!$("#code").val()){
            msg.push('请填写商店的账户号码！');
            $("#code").addClass('err');
        }
        
        if(!$("#currencyID").val()){
            msg.push('请填写商店的账户货币！');
            $("#currencyID").addClass('err');
        }
        
        if(!$("#paytypeID").val()){
            msg.push('请填写商店的支付方式！');
            $("#paytypeID").addClass('err');
        }
        
        if(!$("#owner").val()){
            msg.push('请填写商店的账户拥有人！');
            $("#owner").addClass('err');
        }
        
        if(msg.length > 0){
            alertError(msg);
            return false;
        }else{
            $("form").submit();
        }
    }

     function toCancel(){
         redirect_alert("{{MSG_LEAVE_WITHOUT_SAVING}}","{{url_for('.view',action='account')}}");
    }
//]]>
 </script>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">主面板</a></li>
          <li class="active">财务管理</li>
        </ol>
    </div>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="toSubmit()">{{BTN_SUBMIT}}</button></div>
            <div class="btn-group"><button class="btn btn-inverse" onclick="toSubmit()">{{BTN_CANCEL}}</button></div>
        </div>
    </div>
    <div class="row">
        <form class="" method='POST' action="{{url_for('bpFin.view',action='addAccount')}}"  enctype="multipart/form-data">
        <fieldset>
            <legend>账户信息</legend>
                <div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="name">账户名称</label></label>
                            <div class="controls"><input type="text" name="name" id="name" value=""/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="code">账户银行</label></label>
                            <div class="controls">
                                {{mymacros.select('bankID',list=getMaster('Bank','name'),value=None)}}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="code">账户号码</label></label>
                            <div class="controls"><input type="text" name="code" id="code" value=""/></div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="owner">账户拥有人</label></label>
                            <div class="controls"><input type="text" name="owner" id="owner" value=""/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="currencyID">账户货币</label></label>
                            <div class="controls">
                                <select name="currencyID" id="currencyID">
                                    {% for c in getMaster('Currency') %}
                                        {% if c.isDefault %}
                                            <option value="{{c.id}}" selected="selected">{{c}}</option>
                                        {% else %}
                                            <option value="{{c.id}}">{{c}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="paytypeID">支付方式</label></label>
                            <div class="controls">
                                <select name="paytypeID" id="paytypeID">
                                    {% for p in getMaster('Paytype') %}
                                        <option value="{{p.id}}">{{p}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="amount">余额</label></label>
                            <div class="controls"><input type="text" name="amount" id="amount" value="0" class="num"/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="remark">备注</label></label>
                            <div class="controls"><textarea name="remark" id="remark"></textarea></div>
                        </div>
                    </div>
                </div>
        </fieldset>
        </form>
    </div>
</div>
{% endblock %}

sys2do/templates/fin/account_update.html
{% extends "master.html" %}
{% block subtitle %} - 主面板 - 财务管理 - 更新账户{% endblock %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        if(!$("#name").val()){
            msg.push('请填写商店的账户名称！');
            $("#name").addClass('err');
        }
        
        if(!$("#bankID").val()){
            msg.push('请填写商店的账户银行！');
            $("#bankID").addClass('err');
        }
        
        if(!$("#code").val()){
            msg.push('请填写商店的账户号码！');
            $("#code").addClass('err');
        }
        
        if(!$("#currencyID").val()){
            msg.push('请填写商店的账户货币！');
            $("#currencyID").addClass('err');
        }
        
        if(!$("#paytypeID").val()){
            msg.push('请填写商店的支付方式！');
            $("#paytypeID").addClass('err');
        }
        
        if(!$("#owner").val()){
            msg.push('请填写商店的账户拥有人！');
            $("#owner").addClass('err');
        }
        
        if(msg.length > 0){
            alertError(msg);
            return false;
        }else{
            $("form").submit();
        }
    }

     function toCancel(){
         redirect_alert("{{MSG_LEAVE_WITHOUT_SAVING}}","{{url_for('.view',action='account')}}");
    }
//]]>
 </script>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">主面板</a></li>
          <li class="active">财务管理</li>
        </ol>
    </div>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="toSubmit()">{{BTN_SUBMIT}}</button></div>
            <div class="btn-group"><button class="btn btn-inverse" onclick="toSubmit()">{{BTN_CANCEL}}</button></div>
        </div>
    </div>
    <div class="row">
        <form class="" method='POST' action="{{url_for('bpFin.view',action='updateAccount')}}"  enctype="multipart/form-data">
        <input type="hidden" name="id" value="{{obj.id}}"/>
        <fieldset>
            <legend>账户信息</legend>
                <div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="name">账户名称</label></label>
                            <div class="controls"><input type="text" name="name" id="name" value="{{obj.name}}"/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="code">账户银行</label></label>
                            <div class="controls">
                                {{mymacros.select('bankID',list=getMaster('Bank','name'),value=obj.bankID)}}
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="code">账户号码</label></label>
                            <div class="controls"><input type="text" name="code" id="code" value="{{obj.code|f}}"/></div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="owner">账户拥有人</label></label>
                            <div class="controls"><input type="text" name="owner" id="owner" value="{{obj.owner|f}}"/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="currencyID">账户货币</label></label>
                            <div class="controls">
                                <select name="currencyID" id="currencyID">    
                                    {% for c in getMaster('Currency') %}
                                        {% if c.id == obj.currencyID %} 
                                            <option value="{{c.id}}" selected="selected">{{c}}</option>
                                        {% else %}
                                            <option value="{{c.id}}">{{c}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="paytypeID">支付方式</label></label>
                            <div class="controls">
                                <select name="paytypeID" id="paytypeID">
                                    {% for p in getMaster('Paytype') %}
                                        {% if p.id == obj.paytypeID %}
                                            <option value="{{p.id}}" selected="selected">{{p}}</option>
                                        {% else %}
                                            <option value="{{p.id}}">{{p}}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="control-group">
                            <label class="control-label"><label for="amount">余额</label></label>
                            <div class="controls"><input type="text" name="amount" id="amount" value="{{obj.amount}}" class="num"/></div>
                        </div>
                        <div class="control-group">
                            <label class="control-label"><label for="remark">备注</label></label>
                            <div class="controls"><textarea name="remark" id="remark">{{obj.remark|f}}</textarea></div>
                        </div>
                    </div>
                </div>
        </fieldset>
        </form>
    </div>
</div>
{% endblock %}

sys2do/templates/fin/add_in.html
{% extends "master.html" %}
{% block subtitle %} - 财务管理 - 创建应收账单{% endblock %}

{% block extCSS %}
<style type="text/css">
    .tmp,.atmtemplate{
        display : none;
    }
</style>
{% endblock %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    var index = 11;
    function addItem(){
        index +=1 ;
        var tmp = $(".tmp").clone();
        tmp.removeClass("tmp").addClass("done");
        $("input,textarea,select",tmp).each(function(){
            var t = $(this);
            var n = t.attr("name");
            t.attr("name",n.replace("_x","_"+index));
        });
        $("#dtls_tb").append(tmp);
    }
    
    function delItem(obj){
        var t = $(obj);
        $(t.parents("tr")[0]).remove();
    }

    
    function toSubmit(){
        $('form').submit();
    } 
    
    function toCancel(){
        redirect_alert("{{MSG_LEAVE_WITHOUT_SAVING}}","{{url_for('bpFin.view',action='index_in')}}")
    }  
//]]>
</script>
{% endblock %}


{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">基础信息</a></li>
          <li><a href="{{url_for('bpFin.view',action='index_in')}}">财务管理</a></li>
          <li class="active">创建应收账单</li>
        </ol>
    </div>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-default" onclick="addItem()">增加项目</button></div>
            <div class="btn-group"><button class="btn btn-primary" onclick="toSubmit()">{{BTN_SUBMIT}}</button></div>
            <div class="btn-group"><button class="btn btn-inverse" onclick="toCancel()">{{BTN_CANCEL}}</button></div>
        </div>
    </div>
    <div class="row">             
        <form class="" method='POST' action="{{url_for('bpFin.view',action='saveNew')}}"  enctype="multipart/form-data">
        <fieldset>
            <legend>应收账单详情</legend>
            <input type="hidden" name="direction" value="{{FIN_IN}}"/>
            <div class="col-md-4">
                 <div class="control-group controls-row">
                    <label for="invoiceNo" class="control-label"><label for="invoiceNo">发票号码</label></label>
                    <div class="controls"><input type="text" name="invoiceNo" id="invoiceNo"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="issueTo" class="control-label"><label for="issueTo">发票抬头</label></label>
                    <div class="controls"><input type="text" name="issueTo" id="issueTo"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="refer" class="control-label"><label for="refer">涉及</label></label>
                    <div class="controls"><input type="text" name="refer" id="refer"/></div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="createTime" class="control-label"><label for="createTime">开票时间</label></label>
                    <div class="controls"><input type="text" name="createTime" id="createTime" class="datepicker" value="{{now()|fd}}"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="createBy" class="control-label"><label for="createBy">经办人</label></label>
                    <div class="controls"><input type="text" name="createBy" id="createBy" readonly="true" value="{{session['user_profile']['name']}}"/></div>
                </div>
                <div class="control-group controls-row">
                    <label for="remark" class="control-label"><label for="remark">备注</label></label>
                    <div class="controls"><textarea name="remark" id="remark"></textarea></div>
                </div>               
            </div>
            <div class="col-md-4">
                <div class="control-group controls-row">
                    <label for="amount" class="control-label"><label for="amount">总金额<span style='color:red'>*</span></label></label>
                    <div class="controls"><input type="text" name="amount" id="amount" class="num"/></div>
                </div>
                <div class="control-group">
                  <label class="control-label" for="attachment">附件</label>
                  <div class="controls">
                      <ul id="atmul" class="list-unstyled">
                          <li><input type="file" name="atm_10"/><a href="#" onclick="addAtm('atmtemplate','atmmk','#atmul')"><i class="glyphicon glyphicon-plus"></i></a></li>
                          <li class="atmtemplate"><input type="file" name="atm_x"/><a href="#" onclick="delAtm(this,'atmmk')"><i class="glyphicon glyphicon-minus"></i></a></li>
                      </ul>
                  </div>
                </div>             
            </div> 
            <div class="col-md-12">
                <table class="table table-bordered" id="dtls_tb">
                    <thead>
                        <tr>
                            <td>&nbsp;</td>
                            <td class="col-md-2">项目名称</td>
                            <td>项目描述</td>
                            <td class="col-md-2">单价</td>
                            <td class="col-md-1">数量</td>
                            <td class="col-md-2">金额</td>
                            <td class="col-md-2">备注</td>
                        </tr>
                    </thead>
         
                    <tbody>
                        <tr class="done">
                            <td><a href="#" onclick="delItem(this)"><i class="glyphicon glyphicon-remove"></i></a></td>
                            <td><input type="text" name="itemName_10" class="col-md-2"/></td>
                            <td><textarea name="desc_10" class="col-md-2"></textarea></td>
                            <td><input type="text" name="price_10" class="col-md-2 num"/></td>
                            <td><input type="text" name="qty_10" class="col-md-1 num"/></td>
                            <td><input type="text" name="amount_10" class="col-md-2 amount num"/></td>
                            <td><textarea name="remark_10" class="col-md-2"></textarea></td>
                        </tr>
                        <tr class="tmp">
                            <td><a href="#" onclick="delItem(this)"><i class="glyphicon glyphicon-remove"></i></a></td>
                            <td><input type="text" name="itemName_x" class="col-md-2"/></td>
                            <td><textarea name="desc_x" class="col-md-2"></textarea></td>
                            <td><input type="text" name="price_x" class="col-md-2 num"/></td>
                            <td><input type="text" name="qty_x" class="col-md-1 num"/></td>
                            <td><input type="text" name="amount_x" class="col-md-2 amount num"/></td>
                            <td><textarea name="remark_x" class="col-md-2"></textarea></td>
                        </tr>
                    </tbody>                
                </table>
            </div>
        </fieldset>
        </form>
    </div>
    
   
</div>
{% endblock %}

sys2do/templates/fin/view_log.html
{% extends "master.html" %}
{% block subtitle %} - 财务管理 - 账单详情{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="{{url_for('bpRoot.view')}}">基础信息</a></li>
          {% if obj.direction == FIN_IN %}
            <li><a href="{{url_for('bpFin.view',action='index_in')}}">
          {% elif obj.direction == FIN_OUT %}
            <li><a href="{{url_for('bpFin.view',action='index_out')}}">
          {% endif %}
                财务管理</a></li>
          <li class="active">账单详情</li>
        </ol>
    </div>
    <div class="row">
        <ul class="nav nav-tabs">
          <li><a href="{{url_for('.view',action='view',id=obj.id)}}">账单详情</a></li>
          <li class="active"><a href="#">日志记录</a></li>
        </ul>
    </div>
    <div class="row">
        {{mymacros.render_log(obj.viewLog())}}
    </div> 
   
</div>





{% endblock %}