sys2do/templates/__init__.py
# -*- coding: utf-8 -*-

sys2do/views/auth.py
# -*- coding: utf-8 -*-
'''
###########################################
#  Created on 2011-12-5
#  @author: cl.lam
#  Description:
###########################################
'''
import traceback
from hashlib import sha1
from datetime import datetime as dt, timedelta
from flask import session, g, render_template
from flask.helpers import url_for, flash
from werkzeug.utils import redirect
from flask.blueprints import Blueprint
from sqlalchemy.sql.expression import and_
from flask_wtf import Form, HiddenField, TextField, required, email, PasswordField, equal_to

from sys2do.util.decorator import templated
from sys2do.util.common import _g, _gld, upload, sendMail
from sys2do.model import db, User, Group, qry
from sys2do.constant import MESSAGE_ERROR, MSG_USER_NOT_EXIST, \
    MSG_WRONG_PASSWORD, MSG_RECORD_NOT_EXIST, MSG_NOT_ALL_PARAMS_OK, \
    LOG_TYPE_UPDATE, MSG_UPDATE_SUCC, MESSAGE_INFO, MSG_SERVER_ERROR, \
    MSG_EMAIL_NOT_EXIST, MSG_SEND_EMAIL_GET_PASSWORD, MSG_RESET_PASSWORD_LINK_EXPIRY, \
    MSG_RESET_PASSWORD_SUCCESS, MSG_WRONG_CAPTCHA
from flask.globals import request
from sqlalchemy.orm.exc import NoResultFound
from sys2do.model.master import ShopProfile, Shop
from sys2do.util.captcha import Captcha
from sys2do.util.logic_helper import getPermission, getCurrentUserID
from sys2do.model.system import SysLog


__all__ = ['bpAuth']

index_url = lambda : url_for( 'bpRoot.view', action = "index" )

bpAuth = Blueprint( 'bpAuth', __name__ )


@bpAuth.route( '/login', methods = ['GET', 'POST'] )
@templated( "login.html" )
def login():
    if session.get( 'login', None ): return redirect( index_url() )

    if request.method == "GET" : return {}

    msgs = []
    # 验证码输入是否正确
    captcha_input = _g( 'captcha' )
    captcha = Captcha( session = session )
    if not captcha_input or not captcha.validate( captcha_input ):
        msgs.append( MSG_WRONG_CAPTCHA )

    try:
        u = User.identify( _g( 'name' ) )
    except:
#         _error( traceback.print_exc() )
        flash( MSG_USER_NOT_EXIST, MESSAGE_ERROR )
    else:
        if not _g( 'password' ):
            msgs.append( MSG_WRONG_PASSWORD )

        if len( msgs ) > 0:
            flash( '<br/>'.join( msgs ), MESSAGE_ERROR )
            return redirect( url_for( 'bpAuth.login', next = _g( 'next' ) ) )
        elif not u.validatePassword( _g( 'password' ) ):
            flash( MSG_WRONG_PASSWORD, MESSAGE_ERROR )
            return redirect( url_for( 'bpAuth.login', next = _g( 'next' ) ) )
        else:
            # fill the info into the session
            loginUser( u )
            if _g( 'next' ) : return redirect( _g( 'next' ) )
            return redirect( index_url() )


@bpAuth.route( '/get_captcha' )
def get_captcha():
    captcha = Captcha( session = session, img_width = 120, img_height = 40 )
    return captcha.get_image()

@bpAuth.route( '/logout' )
def logout():
    logoutUser()
    return redirect( url_for( 'bpAuth.login' ) )

@bpAuth.route( '/forget_password', methods = ['GET', 'POST'] )
@templated( 'forget_password.html' )
def forget_password():
    '''
    找回密码流程：
        Step1:  .../auth/forget_password?t=input_email method=get 输入邮箱, 点击确认
        Step2:  .../auth/forget_password?t=input_email method=post 确认此邮箱的用户存在，
                通过sha1加密（验证用户身份）后和当前时间（验证链接是否失效）一起保存数据库，并发送邮件
        Step3:  .../auth/forget_password?t=reset_password&forget_pw_sha1=? method=get打开邮件，并点击链接，
                验证sha1和时间是否失效，通过则跳转到重置密码
        Step4:  .../auth/forget_password?t=reset_password method=post 重置密码，成功，重新登录系统
    '''
    t = _g( 't' )

    if t not in ['input_email', 'reset_password']:
        return redirect( url_for( 'bpAuth.login' ) )

    if t == 'input_email':    # 输入邮箱找回密码
        form = EmailForm()
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            user = User.byEmail( email )
            if not user:
                flash( MSG_EMAIL_NOT_EXIST, MESSAGE_ERROR )
                return redirect( url_for( 'bpAuth.forget_password', t = t ) )
            user.forget_pw_time = dt.now()
            user.forget_pw_sha1 = sha1( email + str( user.forget_pw_time ) ).hexdigest()
            db.add( user )
            db.commit()
            reset_url = request.url_root[:-1] + url_for( 'bpAuth.forget_password', t = 'reset_password', forget_pw_sha1 = user.forget_pw_sha1 )
            subject = u'雅菡珠宝 - 找回密码'
            html = [
                u'亲爱的用户 %s 您好,' % user.name,
                u'<br/><div style="margin-left:24px;">请您点击下面的链接来找回密码： <a href="%s">%s</a>' % ( reset_url, reset_url ),
                u'<br/>为了保证您的帐号安全，该链接仅<font color="red">三天</font>内有效。',
                u'如果该链接已经失效，请重新找回密码。</div>'
            ]
            sendMail( [email], subject, None, '<br/>'.join( html ) )
            flash( MSG_SEND_EMAIL_GET_PASSWORD, MESSAGE_INFO )
        return {'form': form, 't': t}

    if t == 'reset_password':    # 重置密码
        if not _g( 'forget_pw_sha1' ): return redirect( url_for( 'bpAuth.login' ) )    # args:forget_pw_sha1 is required.
        form = ResetPasswordForm()
        form.forget_pw_sha1.data = _g( 'forget_pw_sha1' )
        if request.method == 'POST' and form.validate_on_submit():
            user = User.getBy( [User.forget_pw_sha1 == form.forget_pw_sha1.data] )
            if user and ( dt.now() - user.forget_pw_time ) < timedelta( days = 3 ) :    # 该用户存在，且链接有效期在3天之内
                user.password = form.password.data
                user.updateTime = dt.now()
                db.commit()
                flash( MSG_RESET_PASSWORD_SUCCESS, MESSAGE_INFO )
            else:
                flash( MSG_RESET_PASSWORD_LINK_EXPIRY, MESSAGE_ERROR )
                return redirect( url_for( 'bpAuth.forget_password', t = 'input_email' ) )
        return {'form': form, 't': t, 'forget_pw_sha1': _g( 'forget_pw_sha1' )}



def loginUser( u ):
    session['user_profile'] = u.populate()
    permissions = set()
    for g in u.groups:
        for p in g.permissions:
            permissions.add( p.name )
    session['user_profile']['groups'] = [g.name for g in u.groups]
    session['user_profile']['permissions'] = list( permissions )
    session['login'] = True
    # If set to True the session lives for permanent_session_lifetime seconds.
    # The default is 31 days. If set to False (which is the default) the session
    # will be deleted when the user closes the browser.
    session.permanent = False
    u.last_login = dt.now()

    gids = set( [unicode( g.id ) for g in u.groups] )
    shops = []
    if getPermission( 'SHOP_VIEW_ALL' ):
        shops = [( unicode( s.id ), unicode( s ) ) for s in qry( Shop ).filter( and_( Shop.active == 0 ) )]
    else:
        for sp in qry( ShopProfile ).filter( ShopProfile.active == 0 ):
            tmp = set( sp.groupIDs or [] )
            if len( gids.intersection( ( tmp ) ) ) > 0 : shops.append( ( unicode( sp.shopID ), unicode( sp.shop ) ) )
#     session['shops'] = shops
    if shops :
        session['currentShopID'] = shops[0][0]
    else:
        session['currentShopID'] = None
    db.commit()



def logoutUser():
    session.pop( 'login', None )
    session.pop( 'user_profile', None )
    session.pop( 'currentShopID', None )




@bpAuth.route( '/changePW', methods = ['GET', 'POST'] )
@templated( 'change_pw.html' )
def changePW():
    if request.method == 'GET':  return {}
    uid = getCurrentUserID()
    obj = User.get( uid )

    url = url_for( 'bpAuth.changePW' )
    if not obj :
        flash( MSG_RECORD_NOT_EXIST, MESSAGE_ERROR )
        return redirect( url )

    params = _gld( 'oldpassword', 'newpassword', 'repassword' )

    if not all( params.values() ):
        flash( MSG_NOT_ALL_PARAMS_OK, MESSAGE_ERROR )
    elif params['newpassword'] != params['repassword']:
        flash( MSG_NOT_ALL_PARAMS_OK, MESSAGE_ERROR )
    elif not obj.validatePassword( params['oldpassword'] ):
        flash( MSG_WRONG_PASSWORD, MESSAGE_ERROR )
    else:
        try:
            obj.password = params['newpassword']
            obj.updateTime = dt.now()
            db.add( SysLog( refClz = obj.__class__.__name__, type = LOG_TYPE_UPDATE, refID = obj.id, remark = '修改密码' ) )
            flash( MSG_UPDATE_SUCC, MESSAGE_INFO )
            db.commit()
        except:
            flash( MSG_SERVER_ERROR, MESSAGE_ERROR )
            db.rollback()

    return redirect( url )





@bpAuth.route( '/changePro', methods = ['GET', 'POST'] )
@templated( 'change_profile.html' )
def changePro():
    uid = getCurrentUserID()
    obj = User.get( uid )
    if request.method == 'GET':  return {'obj' : obj}

    params = _gld( 'email', 'phone', 'mobile' )
    try:
        obj.update( params )
        try:
            img = upload( 'imageURL' )
            obj.imageURL = img.url
        except:
            traceback.print_exc()
            pass

        db.add( SysLog( refClz = obj.__class__.__name__, type = LOG_TYPE_UPDATE, refID = obj.id, remark = '修改用户资料' ) )
        flash( MSG_UPDATE_SUCC, MESSAGE_INFO )
        db.commit()
    except:
        db.rollback()
        flash( MSG_SERVER_ERROR, MESSAGE_ERROR )

    return redirect( url_for( 'bpAuth.changePro' ) )



@bpAuth.route( '/viewLog', methods = ['GET', 'POST'] )
@templated( 'view_log.html' )
def viewLog():
    uid = getCurrentUserID()
    obj = User.get( uid )
    if not obj:
        flash( MSG_RECORD_NOT_EXIST, MESSAGE_ERROR )
        return redirect( url_for( 'bpRoot.view' ) )
    return {'obj' : obj}



class EmailForm( Form ):
    email = TextField( u'请您输入邮箱', validators = [required( message = u'必填' ), email( message = u'不是合法的邮箱地址' )] )


class ResetPasswordForm( Form ):
    forget_pw_sha1 = HiddenField( 'forget_pw_sha1', validators = [required( message = u'必填' )] )
    password = PasswordField( u'密码', validators = [required( message = u'必填' )] )
    password_confirm = PasswordField( u'重复密码', validators = [required( message = u'必填' ), equal_to( 'password', message = u'两次输入的密码不同' )] )

sys2do/views/member.py
# -*- coding: utf-8 -*-
'''
Created on 2013-4-11

@author: cl.lam
'''
import traceback
import flask
from flask import current_app as app
from flask import g, render_template, flash, session, redirect, url_for, request, request_finished, jsonify
from flask.blueprints import Blueprint

from sys2do.views import BasicView
from sys2do.util.decorator import templated, loginRequired, allPermission
from sys2do.model import db
from sys2do.model.master import Member
from sys2do.model.system import SysLog

from sys2do.util.logic_helper import getCurrentShopID, getCurrentShop, checkLogin
from sys2do.util.common import _g
from sys2do.constant import *

from ext.view import extract_inline_list

__all__ = ['bpMem']


bpMem = Blueprint( 'bpMem', __name__, )

@bpMem.before_request
def addActivetab():
    session[TAB_FLAG] = TAB_HOME

@bpMem.before_request
def _b():
    return checkLogin()

class MemberView( BasicView ):

    template_folder = 'mem'

    @templated( "index.html" )
    def index( self ):
        form = None
        if request.method == 'POST':
            form = SrhForm( request.form )
            session[url_for( '.view' )] = form
        else:
            form = session.get( url_for( '.view' ), SrhForm( request.form ) )
        form.url = url_for( '.view' )
        cds = [Member.shopID == getCurrentShopID(), Member.active == ACTIVE]
        if form.no.data: cds.append( Member.no.like( '%%%s%%' % form.no.data ) )
        if form.name.data: cds.append( Member.name.like( '%%%s%%' % form.name.data ) )
        if form.tel.data: cds.append( Member.no.like( '%%%s%%' % form.tel.data ) )
        return {'result': Member.findBy( cds ), 'form': form}

    @templated( 'add.html' )
    def add( self ):
        obj = Member.init()
        return {'shop': getCurrentShop(), 'obj': obj, 'fromAction': 'add'}

    @templated( 'add.html' )
    def edit( self ):
        obj = Member.getBy( [Member.id == _g( 'id' )] )
        return {'shop': getCurrentShop(), 'obj': obj, 'fromAction': 'edit'}

    @templated( 'view.html' )
    def view( self ):
        obj = Member.getBy( [Member.id == _g( 'id' )] )
        return {'shop': getCurrentShop(), 'obj': obj}

    @templated( 'view_log.html' )
    def viewLog( self ):
        obj = Member.getBy( [Member.id == _g( 'id' )] )
        return {'shop': getCurrentShop(), 'obj': obj}

    @templated( 'view_so.html' )
    def viewSO( self ):
        obj = Member.getBy( [Member.id == _g( 'id' )] )
        return {'shop': getCurrentShop(), 'obj': obj}

    def save( self ):
        if request.method == 'POST':
            kw = request.form.to_dict()
            kw = extract_inline_list( 'mem', **kw )
            obj = None
            try:
                if kw['fromAction'] == 'add':
                    obj = Member.saveNew( **kw['mem'] )
                    db.add( SysLog( refClz = obj.__class__.__name__, type = LOG_TYPE_CREATE, refID = obj.id, ) )
                    flash( MSG_SAVE_SUCC, MESSAGE_INFO )
                elif kw['fromAction'] == 'edit':
                    obj = Member.get( kw['mem']['id'] )
                    obj.saveEdit( **kw['mem'] )
                    db.add( SysLog( refClz = obj.__class__.__name__, type = LOG_TYPE_UPDATE, refID = obj.id, ) )
                    flash( MSG_UPDATE_SUCC, MESSAGE_INFO )
                db.commit()
                return redirect( url_for( '.view', action = 'view', id = obj.id ) )
            except Exception, e:
                flash( MSG_SERVER_ERROR, MESSAGE_ERROR )
                self._error( traceback.format_exc() )
                db.rollback()
                return redirect( url_for( '.view', action = 'index' ) )
        else:
            return redirect( url_for( '.view', action = 'index' ) )

    def searchMem( self ):
        return jsonify( members = [i.no for i in Member.findBy( shopID = getCurrentShopID() )] )

    def getMem( self ):
        member = Member.getBy( [Member.no == _g( 'no' )] )
        return jsonify( product = ( member.toJson() if member else None ) )

bpMem.add_url_rule( '/', view_func = MemberView.as_view( 'view' ), defaults = {'action':'index'} )
bpMem.add_url_rule( '/<action>', view_func = MemberView.as_view( 'view' ) )

from wtforms import Form, TextField, SelectField
from sys2do.util.wt_helper import MyDateField

class SrhForm( Form ):
    no = TextField( u'会员编号', )
    name = TextField( u'姓名', )
    tel = TextField( u'电话', )

sys2do/templates/change_profile.html
{% extends "master.html" %}
{% block subtitle %} - 修改用户资料{% endblock %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        
        if(msg.length > 0){
            alertError(msg);        
            return false;            
        }else{
            $("form").submit();
        }
            
    }
    
    function toCancel(){
        redirect_alert('{{MSG_LEAVE_WITHOUT_SAVING}}',"{{url_for('bpRoot.view')}}");
    }
//]]>
</script>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="#">用户</a></li>
          <li class="active">用户资料</li>
        </ol>
    </div>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#">用户资料</a></li>
      <li><a href="{{url_for('bpAuth.changePW')}}">修改密码</a></li>
      <li><a href="{{url_for('bpAuth.viewLog')}}">日志记录</a></li>
    </ul>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="return toSubmit()">确认</button></div>
            <div class="btn-group"><button class="btn btn-default" onclick="return toCancel()">取消</button></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <ul class="img-thumbnails">
              <li class="col-md-3">
                <div class="img-thumbnail">
                  {% if obj.imageURL %}
                      <img data-src="" alt="" style="width: 160px; height: 120px;" src="{{obj.imageURL}}">
                  {% else %}
                      <img data-src="" alt="" style="width: 160px; height: 120px;" src="">
                  {% endif %}
                </div>
              </li>
            </ul>
        </div>
        <div class="col-md-9">
            <form class="form-horizontal" action="{{url_for('bpAuth.changePro')}}" method="post"  enctype="multipart/form-data">
                <div class="control-group">
                    <label class="control-label" for="name">用户名</label>
                    <div class="controls">
                      <input type="text" id="name" placeholder="用户名" name="name" value="{{obj.name}}" readonly="true">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="email">电子邮件</label>
                    <div class="controls">
                      <input type="text" id="email" placeholder="电子邮件" name="email" value="{{obj.email|f}}">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="phone">电话</label>
                    <div class="controls">
                      <input type="text" id="phone" placeholder="电话" name="phone" value="{{obj.phone|f}}">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="mobile">手机</label>
                    <div class="controls">
                      <input type="text" id="mobile" placeholder="手机" name="mobile" value="{{obj.mobile|f}}">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="mobile">头像</label>
                    <div class="controls">
                      <input type="file" id="imageURL" placeholder="头像" name="imageURL" value="">
                    </div>
                </div>
                
          </form>
        </div>
    </div>
</div>
{% endblock %}

sys2do/templates/change_pw.html
{% extends "master.html" %}
{% block subtitle %} - 修改密码{% endblock %}

{% block extJS %}
<script language="JavaScript" type="text/javascript">
//<![CDATA[
    function toSubmit(){
        var msg = [];
        clearMsg();
        $(".err").removeClass('err');
        
        var oldp = $("#oldpassword");
        if(!oldp.val()){ 
            msg.push('请输入旧的密码！');
            oldp.addClass('err'); 
        }
        
        var newp = $("#newpassword");
        if(!newp.val()){ 
            msg.push('请输入新的密码！');
            newp.addClass('err'); 
        }
        
        var renewp = $("#repassword");
        if(!renewp.val()){ 
            msg.push('请输入确认的密码！'); 
            renewp.addClass('err'); 
        }
        
        if(newp.val() != renewp.val() ){ msg.push('请确保新的密码与确认密码相同！'); }
        if(msg.length > 0){
            alertError(msg);        
            return false;            
        }else{
            //$("form").submit();
        }
            
    }
    
    function toCancel(){
        redirect_alert('{{MSG_LEAVE_WITHOUT_SAVING}}',"{{url_for('bpRoot.view')}}");
    }
//]]>
</script>
{% endblock %}

{% block main %}
<div class="container">
    <div class="row">
        <ol class="breadcrumb">
          <li><a href="#">用户</a></li>
          <li class="active">用户资料</li>
        </ol>
    </div>
    <ul class="nav nav-tabs">
      <li><a href="{{url_for('bpAuth.changePro')}}">用户资料</a></li>
      <li class="active"><a href="#">修改密码</a></li>
      <li><a href="{{url_for('bpAuth.viewLog')}}">日志记录</a></li>
    </ul>
    <div class="row">
        <div class="btn-toolbar pull-right">
            <div class="btn-group"><button class="btn btn-primary" onclick="return toSubmit()">确认</button></div>
            <div class="btn-group"><button class="btn btn-default" onclick="return toCancel()">取消</button></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <form class="form-horizontal" action="{{url_for('bpAuth.changePW')}}" method="post">
                <div class="control-group">
                    <label class="control-label" for="oldpassword">旧密码</label>
                    <div class="controls">
                      <input type="password" id="oldpassword" placeholder="旧密码" name="oldpassword">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="newpassword">新密码</label>
                    <div class="controls">
                      <input type="password" id="newpassword" placeholder="旧密码" name="newpassword">
                    </div>
                </div>
                
                <div class="control-group">
                    <label class="control-label" for="repassword">确认密码</label>
                    <div class="controls">
                      <input type="password" id="repassword" placeholder="确认密码" name="repassword">
                    </div>
                </div>
          </form>
      </div>
    </div>
</div>
{% endblock %}

sys2do/templates/header.html
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{url_for('bpRoot.view')}}"><strong>珠宝进销存管理系统</strong></a>
        </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li{{(' class="active"' if getActiveTab()==TAB_HOME else '')|safe}}><a href="{{url_for('bpRoot.view')}}">{{ getShopPro().shop }}</a></li>
                    <li{{(' class="active"' if getActiveTab()==TAB_BASIC else '')|safe}}><a href="{{url_for('bpMas.view')}}">基础信息</a></li>
                    <li{{(' class="active"' if getActiveTab()==TAB_REPORT else '')|safe}}><a href="{{url_for('bpRpt.view')}}">报表</a></li>
                    {% if getAnyPermission(['USER_VIEW','GROUP_VIEW'])%}
                    <li{{(' class="active"' if getActiveTab()==TAB_SETTING else '')|safe}}><a href="{{url_for('bpSys.view')}}">系统设置</a></li>
                    {% endif %}
                    
                    {% if getAllPermission(['SHOP_VIEW_ALL',]) %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" onclick="showShopList()">更多店铺 <b class="caret"></b></a>
                            <ul class="dropdown-menu" id="shoplist">
                                
                            </ul>
                        </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="" href="#"><span class="glyphicon glyphicon-user glyphicon glyphicon-white"></span>&nbsp;{{session['user_profile']['name']}}</a></li>
                     <li class="dropdown">
                         <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                         <ul class="dropdown-menu">
                            <li><a href="{{url_for('bpAuth.changePro')}}"><i class="glyphicon glyphicon-pencil"></i>&nbsp;我的信息</a></li>
                            <li><a href="{{url_for('bpAuth.changePW')}}"><i class="glyphicon glyphicon-lock"></i>&nbsp;修改密码</a></li>
                            <li class="divider"></li>
                            <li><a href="{{url_for('bpAuth.logout')}}"><i class="glyphicon glyphicon-off"></i>&nbsp;退出</a></li>
                        </ul>
                     </li>
                </ul>
            </div>
            <!--/.navbar-collapse -->
    </div>
</div>

sys2do/templates/index.html
{% extends "master.html" %}


{% block main %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <div class="list-group-item active">待办事项</div>
                {{render_todo('待审批采购单','PURCHASE_APPROVE','bpPrh.view')}}
                {{render_todo('待审批销售单','SALE_APPROVE','bpSale.view')}}
                {{render_todo('待审批调拨单','DN_APPROVE','bpTns.view')}}
                {{render_todo('待审批出入库单','INVENTORY_NOTE_APPROVE','bpIvtnt.view')}}
                {{render_todo('待审批应收账单','FIN_IN_APPROVE','bpFin.view')}}
                {{render_todo('待审批应付账单','FIN_OUT_APPROVE','bpFin.view')}}
            </div>
        </div>
        <div class="col-md-9">            
            <div class="row">
                    {% if canSale and getAllPermission(['SALE_VIEW',])%}                                      
                        {{render_module('零售管理',url_for('bpSale.view'),'sale.jpg')}}
                    {% endif %}
                    {% if canPurchase and getAllPermission(['PURCHASE_VIEW',])%}                        
                        {{render_module('采购管理',url_for('bpPrh.view'),'prh.jpg')}}
                    {% endif %}
                    {% if getAllPermission(['DN_VIEW',])%}                        
                        {{render_module('调拨管理',url_for('bpTns.view'),'tns.jpg')}}
                    {% endif %}
                    {% if getAllPermission(['INVENTORY_NOTE_VIEW',])%}                          
                        {{render_module('出入库管理',url_for('bpIvtnt.view'),'ivtnt.jpg')}}
                    {% endif %}
                    {% if getAllPermission(['INVENTORY_VIEW',])%}                        
                         {{render_module('仓位管理',url_for('bpIvt.view'),'ivt.jpg')}}
                    {% endif %}
                    <!--
                     {% if getAllPermission(['RGN_VIEW',])%}

                         {{render_module('退货管理',url_for('bpRg.view'),'aa')}}
                    {% endif %}
                    --> 
                    {% if getAllPermission(['MEMBER_VIEW',])%}                        
                        {{render_module('会员管理',url_for('bpMem.view'),'mem.jpg')}}
                    {% endif %} 
                    {% if getAllPermission(['FIN_IN_VIEW','FIN_OUT_VIEW'])%}                        
                        {{render_module('财务管理',url_for('bpFin.view'),'fin.jpg')}}
                    {% endif %}
                                       
                        {{render_module('单个商品追踪',url_for('bpTrc.view'),'trc.jpg')}}
            </div>
            
        </div> 
    </div>
</div>
{% endblock %}



{% macro render_todo(label,key,view) %}
    {% if getAllPermission([key,])%}
        <div class="list-group-item">
            <span class="badge">{{todo[key].count() }}</span>{{label}}
            <ul class="list-unstyled">
                {% for a in todo[key][:5] %}
                    <li><a href="{{url_for(view,action='view',id=a.id)}}"><i class="glyphicon glyphicon-arrow-right"></i>{{a}}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
{% endmacro %}


{% macro render_module(label,url,img) %}
    <div class="col-md-4" style="padding-bottom: 20px">
        <div class="thumbnail">
          <a href="{{url}}"><img alt="{{label}}" src="{{url_for('static', filename='img/system/%s' %img)}}"></a>
          <div class="caption">
            <h3>{{label}}</h3>
            <p class="text-right"><a href="{{url}}" class="btn btn-primary">{{BTN_ENTER}}</a></p>
          </div>
        </div>
    </div>
{% endmacro %}